### PR TITLE
Fix - #4 - Create dir if it doesn't exist on file log

### LINKED ISSUE #4: [BUG] - Log to file in sub folder is broken
**Description:**

When using the custom C++ logger with a log file path that includes a subdirectory (e.g. `{project-root}/Logs/my-log-file.log`), the logger fails if the `Logs/` directory does not already exist.

Instead of creating the directory automatically, the logger throws an error.

**Steps to Reproduce:**

Configure the logger to write logs to a file with a subdirectory path, for example:

```c
logger.setLogFilePath({project-root}/Logs/my-log-file.log);
```

Make sure the Logs directory does not exist.

Run the application and trigger any log.

**Result:**

The application outputs the following error:

```sh
[Logger Error] Log file path is not set.
```

No log file is created.

**Expected Result:**

The logger should automatically create missing directories in the log file path and successfully write logs to the file.

**Possible Root Cause:**

The logger likely checks only the file path validity and does not handle automatic directory creation when intermediate folders are missing.

### PR DESCRIPTION
**Pull request by viastolfi**
close: #4 

**Context:**

Logging into a non-existing file path was resulting in an early crash.  
The chosen solution in the linked issue is to create the directories directly from the Logger to avoid this.

**Solution:**

The solution I came up with is to use the standard C++ filesystem library.

What is done is to strip the last block of the defined path; this allows us to obtain a relative path representing the directory tree where the log file will be located.  
To do so, we create a `pos` variable to get the position of the last `/` character.  
Then, we use `std::string::npos` to check whether `pos` actually contains a valid position. This ensures that the given path is correct. We also use this check to avoid creating a directory when the path refers to a simple file (e.g. `file.log`).

Finally, we create the directory tree using the `create_directories` function.

**Limitations:**

This solution is highly Unix-dependent and may need improvements to ensure it works properly on Windows environments (e.g. handling the `\\` Windows path syntax).

There is currently no automated test for this change. Since testing this would require creating a complete directory tree, it is not covered by the project's `tests` folder. If you have any ideas on how to implement such tests, feel free to share them.

I am not sure whether this project is open to PRs, but I found it quite interesting and decided to dive into it. Feel free to review this or not — no hard feelings.

Thanks in advance!

### CODE REVIEW

File: include/Logger.h [hunk 1]
```diff
@@ -126,6 +127,13 @@ namespace Xale::Logger
 			LoggerConfig::logFile.close();
         else
         {
+          auto pos = filePath.rfind("/");
+          if (pos != std::string::npos) 
+          {
+            std::filesystem::path fsPath = filePath.substr(0, pos);
+            if (!std::filesystem::exists(fsPath)) 
+              std::filesystem::create_directories(fsPath);
+          }
```
Comment (axdelafuen) [inline include/Logger.h]: Thanks for the change 🙂
Just a small style note: could you reindent this new code to use 4 spaces instead of 2, to stay consistent with the rest of the codebase?

**Review by axdelafuen — CHANGES_REQUESTED** [review]

File: include/Logger.h (hunk 1 above)
Comment (viastolfi) [reply include/Logger.h]: My bad, didn't think of this.

It's fix

**Review by axdelafuen — APPROVED** [review]
LGTM
